### ISSUE TITLE
No Model in Model Folder

### ISSUE THREAD

**Issue by anaghrao-99** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#10]
Hey, 

I was looking at your code and noticed there is no saved model in the model folder. Is there something I am missing? Also when I am trying to train the model myself, I run into the error - 

Traceback (most recent call last):
  File "main.py", line 193, in <module>
    main()
  File "main.py", line 164, in main
    Model.imgSize, Model.maxTextLen, load_aug=True)
  File "/Users/anagh/Downloads/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow-master/src/DataLoader.py", line 79, in __init__
    gtText_list = lineSplit[9].split('|')
IndexError: list index out of range

Please note - I have downloaded the dataset lines.tgz and also have put lines.txt in data folder.

**Comment by padma1144** [comment]
How to modify the paragraph line text recognition

**Comment by padma1144** [comment]
Model snapshot-24 missing in the model directory

**Comment by sushant097** [comment]
@anaghrao-99 model snapshot is not available right now. You have to train it by yourself with passing command line argument.

**Comment by padma1144** [comment]
How to train?

**Comment by sushant097** [comment]
To Train the model from scratch
`python main.py --train`
Make sure you place the dataset in the given folder as in README.md
