### ISSUE TITLE
Recognition error: using generate_random_images(

### ISSUE THREAD

**Issue by imsunnykr** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#11]
Hi Sushant,

I really appreciate your work and need your help.

Under main.py, the solution works perfectly with function - load_different_image()

However, i am trying to create random images by using below function but predicted outcome is always wrong. Please help what is wrong.

```
def generate_random_images():
    imgs = []
    for i in range(1, Model.batchSize):
        imgs.append(np.random.random((Model.imgSize[0], Model.imgSize[1])))
    return imgs


def infer(model, fnImg):
    """ Recognize text in image provided by file path """
    img = preprocessor(cv2.imread(fnImg, cv2.IMREAD_GRAYSCALE), imgSize=Model.imgSize)
    imgs = generate_random_images()
    imgs = [img] + imgs
    batch = Batch(None, imgs)
    recognized = model.inferBatch(batch)  # recognize text
    print("Without` Correction", recognized[0])
    print("With Correction", correct_sentence(recognized[0]))
    return recognized[0]
```

Also, I have tried duplicating the input image 10 times rather than using function like  load_different_image() and generate_random_images() but this way it don't recognize anything. Sharing the example below.

```
def infer(model, fnImg):
    """ Recognize text in image provided by file path """
    img = preprocessor(cv2.imread(fnImg, cv2.IMREAD_GRAYSCALE), imgSize=Model.imgSize)
    batch = Batch(None, [img]*Model.batchSize) #duplicating input image 10 times
    recognized = model.inferBatch(batch)  # recognize text

    print("Without Correction", recognized[0])
    print("With Correction", correct_sentence(recognized[0]))
    return recognized[0]

```
Please Help!!!

**Comment by sushant097** [comment]
I don't know what is going on there. But the concept is to model is trained on batch with different images on a batch such that it is able to recognize the image. 
When you give the same image repeating batchSize then it might not correlate to find the pattern on it. So creating random images should work. But there can be another reason for this.
 You should place the one image or pair of images in front of random images and return the predicted text.
Hope this helps.

**Comment by sushant097** [comment]
Not an active long time.
