### ISSUE TITLE
Issue with the color pictures detection

### ISSUE THREAD

**Issue by abhiymailknp** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#12]
Brother how about also adding teserect functionality with the project as it would be more helpful. I couldn't do the same thingas I am a total beginner at ML and AI .
and ALso please can i get your emailid

**Comment by sushant097** [comment]
You can add tesseract but I have no idea about it. This project uses Grayscale Images as input and the trained model can't find the color images too.
