### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by gayathrisubbu** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#14]
Hi 
I  installed Tensorflow 2.x as 1.8.0 version not available on their repository.
When I running this example I am getting the following error.
AttributeError: module 'tensorflow' has no attribute 'placeholder'

Can you please update the code to support Tensorflow latest version.

Thank you

**Comment by sushant097** [comment]
You should try by yourself, You can see [here.](https://www.tensorflow.org/guide/upgrade)

**Comment by AIGamer28100** [comment]
> Hi
> I installed Tensorflow 2.x as 1.8.0 version not available on their repository.
> When I running this example I am getting the following error.
> AttributeError: module 'tensorflow' has no attribute 'placeholder'
> 
> Can you please update the code to support Tensorflow latest version.
> 
> Thank you

Run `tf_upgrade_v2 --intree Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow/ --outtree Handwritten-Line-Text-Recognition/ --reportfile changesreport.txt` this command to update the file .

**Comment by ACE07-Sev** [comment]
How to run tf_upgrade_v2 --intree Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow/ --outtree Handwritten-Line-Text-Recognition/ --reportfile changesreport.txt ? Do you write it in the terminal or console? What exactly to put in?

**Comment by ACE07-Sev** [comment]
> > Hi
> > I installed Tensorflow 2.x as 1.8.0 version not available on their repository.
> > When I running this example I am getting the following error.
> > AttributeError: module 'tensorflow' has no attribute 'placeholder'
> > Can you please update the code to support Tensorflow latest version.
> > Thank you
> 
> Run `tf_upgrade_v2 --intree Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow/ --outtree Handwritten-Line-Text-Recognition/ --reportfile changesreport.txt` this command to update the file .

How to run it? Can you please give me the full thing and where to put it? Terminal or console?
