### ISSUE TITLE
-- validate error

### ISSUE THREAD

**Issue by dinukakulatunga** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#15]
when I validate the data using python main.py --validate, console give me this error..

![image](https://user-images.githubusercontent.com/32608112/85412847-a9ab2700-b587-11ea-99da-2f98451156af.png)

**Comment by Tamoghna-Saha** [comment]
You need to download the ground truth file of IAM dataset (**lines.txt**) located in the **ascii** folder, but it looks like you have already provided the path correctly.
Print the `lineSplit` and try to see at which point it is breaking wrt to the format of lines.txt

**Comment by lado936** [comment]
you should set lineSplit[8] instead of lineSplit[9], it solved that error for me

**Comment by dinukakulatunga** [comment]
> you should set lineSplit[8] instead of lineSplit[9], it solved that error for me



> You need to download the ground truth file of IAM dataset (**lines.txt**) located in the **ascii** folder, but it looks like you have already provided the path correctly.
> Print the `lineSplit` and try to see at which point it is breaking wrt to the format of lines.txt

**Comment by dinukakulatunga** [comment]
> you should set lineSplit[8] instead of lineSplit[9], it solved that error for me

Thanks for the reply. Yes, I changed the index. It's working now. Thanks

**Comment by varunchach** [comment]
Hi @sushant097 It is nice repository. I tried this on extracting some fields from bank cheques such as (pay to:- , Amount(in words):- ) ,
I found it was not classifying text correctly.I changed btchsize to 50 still didnt work out for me. Any suggestions?

**Comment by sushant097** [comment]
I have no idea about it. You should train from scratch giving the data what this model would work on real time.
