### ISSUE TITLE
Tenserflow 2 suitability

### ISSUE THREAD

**Issue by ArielBatkilin** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#16]
not suitable with tensorflow 2 and above

**Comment by sushant097** [comment]
The current Project is made on Tensorflow 1.8.0, you can upgrade this to TF 2.0 see [here](https://www.tensorflow.org/guide/upgrade). By this, you can easily make this code run on TF 2.0 .
