### ISSUE TITLE
accuracy.txt  and charList.txt not found in Model Directory

### ISSUE THREAD

**Issue by codebugged** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#18]
Hi @sushant097 

Thank you for your repository, its very useful.
I am not able to run python upload.py
as it is unable to find accuracy.txt and charList.txt

Thanks in advance :)

**Comment by sushant097** [comment]
@codebugged download the model files from the given link in readme.md and place all the files inside the model directory.

**Comment by sushant097** [comment]
Hello
Please read the readme.md where I give the link to download the trained
model where charlist.txt and model found place all those files inside the
model directory of your project and run it.
Hope it works.
Best Regards
SUSHANT Gautam

**Comment by varunchach** [comment]
Hi @sushant097  How to download that entire image set from IAM database? Could save lines.txt but not able to download the complete image set does it requires to download lines.tgz file?

**Comment by sushant097** [comment]
Hi, varunchach,
You have to download lines.tgz where all the images are found there.

**Comment by varunchach** [comment]
Hi @sushant097 Thanks for your reply As per your suggestion downloaded image.tgz files But how code will extract images out of it Do we need to add some code for that?

**Comment by sushant097** [comment]
Please manually extract or unzip the folder named data. You can do it on the terminal or use any software for that. Please search on google if you confused about such a thing. Hope it helps you.
