### ISSUE TITLE
How to ediy "maxTextLen" 

### ISSUE THREAD

**Issue by 20IP** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#21]
Hi sushant097, Thank you very much for this article. Although the article is long, you can guide how to edit "maxTextLen". I tried with sentences of any length and got an error.
Thanks!

**Comment by sushant097** [comment]
You should try out changing maxTextLen during preprocessing and confugartion in model.py file. Hope this helps you.
