### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by ACE07-Sev** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#23]
I ran tf_upgrade_v2 --intree Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow/ --outtree Handwritten-Line-Text-Recognition/ --reportfile changesreport.txt but I'm still getting the error. I installed tf-nightly but still same. can you please guide me?

2021-11-21 04:19:05.588993: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-11-21 04:19:05.602350: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
TensorFlow 2.0 Upgrade Script
-----------------------------
Converted 0 files
Detected 0 issues that require attention
--------------------------------------------------------------------------------

Make sure to read the detailed log 'changesreport.txt'

This is what I get.

**Comment by Aditya-017** [comment]
I haven't used the upgrade script so i am not sure about that, but it was working fine. It did give this error "(2021-11-21 04:19:05.602350: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.)"> but was still giving results.

**Comment by sushant097** [comment]
@Aditya-017 comment is correct. Please make sure, you have gpu and required cuda driver installed, or you can run with cpu as configured. 
Hope you solved this issue already. I closed this issue now. Please feel free to open another issue, if the issue persists.
