### ISSUE TITLE
Output wrong

### ISSUE THREAD

**Issue by ACE07-Sev** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#24]
I get this for the test image. is this supposed to happen?

W/O correction
Clothed leat by leaf with the disappoisthet

W correction
Clothes left by leaf with the disappoisthet 

Can please check this out. is it supposed to happen?

**Comment by Aditya-017** [comment]
yes there is function of spelling correction in the project this is the result before and after using that function.

**Comment by ACE07-Sev** [comment]
but it's not giving the same. can't it do better? is it supposed to output this?

**Comment by sushant097** [comment]
@ACE07-Sev Yes. Simple word correction try to correct word to the nearest correct word if possible. Also, currently most of the time it is using greedy based decoder, which is not good enough. But if you retrained accordingly on your variety of samples, the accuracy would improve. You can find better CTC decoder [here](https://github.com/githubharald/CTCDecoder)
