### ISSUE TITLE
specific format required of input images with handwritten text lines?

### ISSUE THREAD

**Issue by chinya07** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#3]
@sushant097 I have handwritten a line on a notebook page. Clicked a picture of it and provided it to the model but it is not recognizing a single word. Does this model require images with strictly white background and black text input images ?

**Comment by sushant097** [comment]
It should recognize the word also. You should provide the grayscale image on the model to recognize.
