### ISSUE TITLE
its about implementation

### ISSUE THREAD

**Issue by santhubaby** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#6]
could you please explain how to implement it on ubuntu 18.04 ?can you guide me the steps needed for implementation  of this project?
eagerly waiting for your answer.

**Comment by sushant097** [comment]
It simple.
1. First, install all the dependency required. Create a virtual environment and install: Tensorflow==1.8.0 ; OpenCv 3, Numpy, EditDistance etcc.
2. Download the dataset as found in IAM dataset as in readme. 
3. Train the model by running main.py `python main.py --train`
4. For prediction change the image file path to load as in: https://github.com/sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow/blob/master/src/DataLoader.py#L26 
5. Install Flask dependency if you need it web GUI as in upload.py.

**Comment by sushant097** [comment]
Inactive issue. I hope this issue is solved.

**Comment by santhubaby** [comment]
Can you please make a video for this since iam getting errors,,, just i
want demo for this... If not possible,, it's ok.
