### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by anush97** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#8]
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    main()
  File "main.py", line 164, in main
    Model.imgSize, Model.maxTextLen, load_aug=True)
  File "C:\Users\hp\Desktop\Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow-master\src\DataLoader.py", line 79, in __init__
    **gtText_list = lineSplit[9].split('|')**
IndexError: list index out of range

**Comment by yashagarwal1999** [comment]
Hey, @anush97 I cloned this repo and was trying to run the file but it said lines.txt not found? Can you help me out with that I am new to DL.
The error was 

  File "main.py", line 193, in <module>
    main()
  File "main.py", line 164, in main
    Model.imgSize, Model.maxTextLen, load_aug=True)
  File "/home/yash/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow-master/src/DataLoader.py", line 59, in __init__
    f = open("../data/" + 'lines.txt')
FileNotFoundError: [Errno 2] No such file or directory: '../data/lines.txt'



To solve it I created an empty file then called lines.txt then and now the error is 

Warning, damaged images found: []
Damaged images expected: ['a01-117-05-02.png', 'r06-022-03-05.png']
Train: 0, Validation: 0
Python: 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609]
Tensorflow: 1.12.0
2020-03-30 19:36:04.021520: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Init with new values
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    main()
  File "main.py", line 169, in main
    train(model, loader)
  File "main.py", line 24, in train
    totalEpoch = loader.trainSamples//Model.batchSize # loader.numTrainSamplesPerEpoch
TypeError: unsupported operand type(s) for //: 'list' and 'int'

**Comment by anush97** [comment]
Hi , sorry to reply late 

you have to download IAM data as mentioned in the instructions of this repo . When you would visit the portal to download IAM data base there is lines.txt already present in lines link. Once you get to that page you have just either copy the text and open a new text file and paste or ctrl+s and name it lines.txt

**Comment by padma1144** [comment]
> Traceback (most recent call last):
> File "main.py", line 193, in
> main()
> File "main.py", line 164, in main
> Model.imgSize, Model.maxTextLen, load_aug=True)
> File "C:\Users\hp\Desktop\Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow-master\src\DataLoader.py", line 79, in **init**
> **gtText_list = lineSplit[9].split('|')**
> IndexError: list index out of range

How to solve this error

**Comment by mohitankoliya** [comment]
gtText_list = lineSplit[8].split('|') try this code

**Comment by dabasjayant** [comment]
> > Traceback (most recent call last):
> > File "main.py", line 193, in
> > main()
> > File "main.py", line 164, in main
> > Model.imgSize, Model.maxTextLen, load_aug=True)
> > File "C:\Users\hp\Desktop\Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow-master\src\DataLoader.py", line 79, in **init**
> > **gtText_list = lineSplit[9].split('|')**
> > IndexError: list index out of range
> 
> How to solve this error

Try using `gtText_list = lineSplit[len(lineSplit)-1].split('|')`
I noticed that `len(lineSplit)` can be 9 or 10 so using a constant might not be a good idea

**Comment by dabasjayant** [comment]
> Hey, @anush97 I cloned this repo and was trying to run the file but it said lines.txt not found? Can you help me out with that I am new to DL.
> The error was
> 
> File "main.py", line 193, in 
> main()
> File "main.py", line 164, in main
> Model.imgSize, Model.maxTextLen, load_aug=True)
> File "/home/yash/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow-master/src/DataLoader.py", line 59, in **init**
> f = open("../data/" + 'lines.txt')
> FileNotFoundError: [Errno 2] No such file or directory: '../data/lines.txt'
> 
> To solve it I created an empty file then called lines.txt then and now the error is
> 
> Warning, damaged images found: []
> Damaged images expected: ['a01-117-05-02.png', 'r06-022-03-05.png']
> Train: 0, Validation: 0
> Python: 3.5.2 (default, Oct 8 2019, 13:06:37)
> [GCC 5.4.0 20160609]
> Tensorflow: 1.12.0
> 2020-03-30 19:36:04.021520: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Init with new values
> Traceback (most recent call last):
> File "main.py", line 193, in 
> main()
> File "main.py", line 169, in main
> train(model, loader)
> File "main.py", line 24, in train
> totalEpoch = loader.trainSamples//Model.batchSize # loader.numTrainSamplesPerEpoch
> TypeError: unsupported operand type(s) for //: 'list' and 'int'

It should be `totalEpoch = len(loader.trainSamples)/Model.batchSize`
@sushant097 Please take a look at these issues. Thanks!

**Comment by sushant097** [comment]
@Jayant11 I will consider these Issues.
