### ISSUE TITLE
Pretrained model in CNN layer

### ISSUE THREAD

**Issue by praveenraj2018** [sushant097/Handwritten-Line-Text-Recognition-using-Deep-Learning-with-Tensorflow#9]
Hi Sushant
Great work. Appreciate.

I have a few questions.

1) Have you ever tried adding a pre-trained model such as VGG, Inception or ResNet at the CNN layer? If so, how was results? What you suggest on adding one? 

2) I have read about MD-LSTM and there are results that gives better improvement when used over BiLSTMs. Any experience or experiments on this work?

3) By the way, have you ever attempted to run the code under GPU or TPU? 

thanks
Raj

**Comment by sushant097** [comment]
I haven't use the pre-trained model yet. But hope that it may or not provide a better result.
MD-LSTM can be great as it directly recognizes the whole paragraph without pre-segmentation into lines [here] but training is difficult and needs lots of tricks on it.
And I have run the code on GPU on the Cloud. You can use a small GPU with a small batch of sizes for training.

[here]: http://www.tbluche.com/files/icdar17_sar.pdf

**Comment by praveenraj2018** [comment]
Thanks Sushant. It was useful.
